version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
        - REDIS_HOST=redis #this is how you set the host to be the service name
        - REDIS_PORT=6379
  redis:
    image: "redis:latest"